apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.appName }}-app
spec:
  port:
    targetPort: {{ .Values.ports.targetPort }}
  to:
    kind: Service
    name: {{ .Values.appName }}-app
    weight: 100
  wildcardPolicy: None
