apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: {{ .Values.ports.port }}
    protocol: TCP
    targetPort: {{ .Values.ports.targetPort }}
  selector:
    app: {{ .Values.appName }}-deploy
  sessionAffinity: None
  type: ClusterIP

