apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: s2i-build-and-deploy
spec:
  params:
    - default: fastapi-quickstart-app
      name: IMAGE_NAME
      type: string
    - default: '1.2'
      name: IMAGE_TAG
      type: string
    - default: 'https://github.com/walkersblog/fastapi-quickstart-project'
      name: GIT_REPO
      type: string
    - default: main
      name: GIT_REVISION
      type: string
    - default: Hello from Pipeline
      name: MESSAGE
      type: string
  workspaces:
    - name: workspace
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: workspace
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
    - name: pytest
      params:
        - name: PYTHON
          value: latest
        - name: SOURCE_PATH
          value: .
        - name: REQUIREMENTS_FILE
          value: requirements.txt
      runAfter:
        - fetch-repository
      taskRef:
        kind: Task
        name: pytest
      workspaces:
        - name: source
          workspace: workspace
    - name: build
      taskRef:
        name: s2i-fastapi
        kind: Task
      runAfter:
        - pytest
      workspaces:
        - name: source
          workspace: workspace
      params:
        - name: IMAGE
          value: image-registry.openshift-image-registry.svc:5000/ocp-fastapi-quickstart-project/$(params.IMAGE_NAME):$(params.IMAGE_TAG)
        - name: TLSVERIFY
          value: "false"
    - name: argocd-task-sync-and-wait
      params:
        - name: application-name
          value: fastapi-quickstart-app
        - name: revision
          value: main
        - name: flags
          value: '--'
        - name: argocd-version
          value: v2.1.6
      runAfter:
        - build
      taskRef:
        kind: Task
        name: argocd-task-sync-and-wait
