apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-workspace-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /home/shares/ocp/shared-workspace
    server: 192.168.1.100
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
