apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-workspace
  namespace: ocp-fastapi-quickstart-project
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
